#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "httpsh"
name = "httpsh on ttyd"
description.en = "Connect to your server via a terminal in the browser"
description.fr = "Connectez-vous à votre serveur via un terminal dans le navigateur web"

version = "1.7.7~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
code = "https://github.com/leshniak/httpsh"
admindoc = "https://github.com/tsl0922/ttyd/wiki/Example-Usage"

fund = "https://github.com/sponsors/tsl0922"
# cpe = "???"

[integration]
yunohost = ">= 11.2.18"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = "not_relevant"

disk = "2M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/httpsh"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

[resources]
    [resources.sources.ttyd]
    format = "whatever"
    extract = false
    rename = "ttyd"

    armhf.url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.armhf"
    armhf.sha256 = "8240c8438b68d3b10b0e1a4e7c914d70fca6a7606b516f40bf40adfa1044d801"

    arm64.url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.aarch64"
    arm64.sha256 = "b38acadd89d1d396a0f5649aa52c539edbad07f4bc7348b27b4f4b7219dd4165"

    i386.url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.i686"
    i386.sha256 = "93e112e19c9c0dcc717e98bdba0f43fc50f0c74ae1ba5b572772c507654ed19c"

    amd64.url = "https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.x86_64"
    amd64.sha256 = "8a217c968aba172e0dbf3f34447218dc015bc4d5e59bf51db2f2cd12b7be4f55"

    autoupdate.strategy = "latest_github_release"
    autoupdate.upstream = "https://github.com/tsl0922/ttyd"
    autoupdate.asset.armhf = "ttyd.armhf"
    autoupdate.asset.arm64 = "ttyd.aarch64"
    autoupdate.asset.i386 = "ttyd.i686"
    autoupdate.asset.amd64 = "ttyd.x86_64"

    [resources.sources.httpsh]
    url = "https://github.com/leshniak/httpsh/archive/0a73bca2880e0f7a75492445641517d11f8d0dcf.tar.gz"
    sha256 = "d50f96a2e4abc518539b69641fce697fd9eed58951b2106dcff977a4dd1884f3"

    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
