#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "httpsh"
name = "httpsh on ttyd"
description.en = "Connect to your server via a terminal in the browser"
description.fr = "Connectez-vous à votre serveur via un terminal dans le navigateur web"

version = "1.7.3~ynh1"

maintainers = ["Salamandar"]

[upstream]
license = "MIT"
code = "https://github.com/leshniak/httpsh"
admindoc = "https://github.com/tsl0922/ttyd/wiki/Example-Usage"

fund = "https://github.com/sponsors/tsl0922"
# cpe = "???"

[integration]
yunohost = ">= 11.1.21"
architectures = ["i386", "amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = "not_relevant"

disk = "2M"
ram.build = "10M"
ram.runtime = "10M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/example"

    [install.init_main_permission]
    type = "group"
    default = "all_users"

    [install.custom_command]
    help.en = "A custom command to run in ttyd instead of `login`. Not recommended to change unless you know what you are doing!"
    help.fr = "Une commande personnalisée à lancer au lieu de `login`. Non recommandé de changer à part si vous savez ce que vous faites !"
    type = "string"
    default = "login"

[resources]
    [resources.sources.httpsh]
    url = "https://github.com/leshniak/httpsh/archive/7d80fac0d48f30e29eaff9a7471399c19ad31518.tar.gz"
    sha256 = "cc7354752e80e1563e80271b7253c0f293346cd46cdfe4858dcf68865e573d30"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ["ttyd"]
